version: 2
jobs:
  build:
    docker:
      - image: kukiri/unityci:2017.3.1f1
    steps:
      - checkout
      - run:
          name: Build Unity
          command: /opt/Unity/Editor/Unity -quit -batchmode -nographics -executeMethod Builder.PerformBuild -projectPath $(pwd) -logFile -buildTarget Android
      - store_artifacts:
          path: test.apk
      - run:
          name: Deploy to Gate
          command: curl -F "file=@test.apk" -F "token=05c54026087b89558ec641d773225d9e52001eec" -F "message=sample" https://deploygate.com/api/users/kukiri/apps
