version: 2
jobs:
  build:
    docker:
      - image: kukiri/unityci:2017.4.0f1
    steps:
      - checkout
      - restore_cache:
          keys:
            - library-
      - run:
          name: Build Unity
          command: /opt/Unity/Editor/Unity -quit -batchmode -nographics -executeMethod Builder.PerformBuild -projectPath $(pwd) -logFile -buildTarget Android
      - store_artifacts:
          path: test.apk
      - save_cache:
          key: library-{{ checksum "Library/assetDatabase3" }}
          paths:
            - Library/
      
